### ISSUE TITLE
Launch darkly adapter doesn't support reconfiguring with an empty/undefined user

### ISSUE THREAD

**Issue by pmdarrow** [tdeekens/flopflip#187] opened 2018-02-15 21:18 UTC
I have my app wrapped with `ConfigureFlopFlip` from `@flopflip/react-broadcast` and configured with `@flopflip/launchdarkly-adapter`. When I log out and pass no user property in `adapterArgs`, the Launch darkly adapter breaks on this line:

https://github.com/tdeekens/flopflip/blob/d85fbdc48b5191a77dc2977ee7a1555fa802dc0f/packages/launchdarkly-adapter/modules/adapter/adapter.js#L183

Shouldn't this be something like the following to support the logout use-case? 
```js
  if (!user || adapterState.user.key !== user.key) {
    adapterState.user = ensureUser(user);
```

**Comment by tdeekens** [comment] 2018-02-15 21:42
Thanks for reporting the issue! I will have a look as soon as I can. 

I think you may be right. By „break“ I guess you mean: „it does not update“? Does your user have an auto generated key or one provided by you?

**Comment by tdeekens** [comment] 2018-02-18 11:59
I see now what the problem is. Will fix now.

**Comment by tdeekens** [comment] 2018-02-18 12:06
Should be fixed in https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Flaunchdarkly-adapter%402.1.2

Let me know if there is anything else behaving unexpected.

**Closed by tdeekens** 2018-02-18 12:06 UTC
